package com.pilot.astrobuddy.domain.model.astro_objects

/**
 * Helper object containing maps defining object type and constellation abbreviations.
 * TO FIX: probably an inefficient way to do this, should be singleton or in the Constants, unless
 * its effectively singleton because its only user is, idk.
 */
object ObjDefinitions {
    val objectTypes: Map<String,String> = hashMapOf(
        "*" to "Star",
        "**" to "Double Star",
        "*Ass" to "Association of Stars",
        "OCl" to "Open Cluster",
        "GCl" to "Globular Cluster",
        "Cl+N" to "Star Cluster & Nebula",
        "G" to "Galaxy",
        "GPair" to "Galaxy Pair",
        "GTrpl" to "Galaxy Triplet",
        "GGroup" to "Galaxy Group",
        "PN" to "Planetary Nebula",
        "HII" to "HII Ionized Region",
        "DrkN" to "Dark Nebula",
        "EmN" to "Emission Nebula",
        "Neb" to "Nebula",
        "RfN" to "Reflection Nebula",
        "SNR" to "Supernova Remnant",
        "Nova" to "Nova Star",
        "NonEx" to "Nonexistent Object",
        "Dup" to "Duplicated Object",
        "Other" to "Other"
    )

    val constellations: Map<String,String> = hashMapOf(
        "Peg" to "Pegasus",
        "Cet" to "Cetus",
        "Psc" to "Pisces",
        "Cas" to "Cassiopeia",
        "And" to "Andromeda",
        "Tri" to "Triangulum",
        "Ari" to "Aries",
        "Per" to "Perseus",
        "Eri" to "Eridanus",
        "Tau" to "Taurus",
        "Cam" to "Camelopardalis",
        "For" to "Fornax",
        "Ori" to "Orion",
        "Aur" to "Auriga",
        "Lep" to "Lepus",
        "Gem" to "Gemini",
        "Mon" to "Monoceros",
        "CMa" to "Canis Major",
        "Cep" to "Cepheus",
        "Lyn" to "Lynx",
        "CMi" to "Canis Minor",
        "Cnc" to "Cancer",
        "Pup" to "Puppis",
        "Hya" to "Hydra",
        "UMa" to "Ursa Major",
        "Leo" to "Leo",
        "Sex" to "Sextans",
        "LMi" to "Leo Minor",
        "Crt" to "Crater",
        "Vir" to "Virgo",
        "Com" to "Coma Berenices",
        "Crv" to "Corvus",
        "CVn" to "Canes Venatici",
        "Dra" to "Draco",
        "Cen" to "Centaurus",
        "Boo" to "Booötes",
        "UMi" to "Ursa Minor",
        "Lib" to "Libra",
        "Se1" to "Serpens Caput",
        "Lup" to "Lupus",
        "CrB" to "Corona Borealis",
        "Her" to "Hercules",
        "Sco" to "Scorpius",
        "Oph" to "Ophiuchus",
        "Ara" to "Ara",
        "Sgr" to "Sagittarius",
        "Se2" to "Serpens Cauda",
        "Sct" to "Scutum",
        "Lyr" to "Lyra",
        "CrA" to "Corona Australis",
        "Aql" to "Aquila",
        "Vul" to "Vulpecula",
        "Cyg" to "Cygnus",
        "Sge" to "Sagitta",
        "Cap" to "Capricornus",
        "Del" to "Delphinus",
        "Aqr" to "Aquarius",
        "Equ" to "Equuleus",
        "Lac" to "Lacerta",
        "Gru" to "Grus",
        "Scl" to "Sculptor",
        "Tuc" to "Tucana",
        "Phe" to "Phoenix",
        "Hyi" to "Hydrus",
        "Hor" to "Horologium",
        "Ret" to "Reticulum",
        "Dor" to "Dorado",
        "Men" to "Mensa",
        "Cae" to "Caelum",
        "Col" to "Columba",
        "Pic" to "Pictor",
        "Car" to "Carina",
        "Vol" to "Volans",
        "Vel" to "Vela",
        "Pyx" to "Pyxis",
        "Ant" to "Antlia",
        "Cha" to "Chamaeleon",
        "Mus" to "Musca",
        "Oct" to "Octans",
        "Aps" to "Apus",
        "Nor" to "Norma",
        "TrA" to "Triangulum Australe",
        "Pav" to "Pavo",
        "Tel" to "Telescopium",
        "Mic" to "Microscopium",
        "Ind" to "Indus",
        "PsA" to "Pisces Austrinus",
        "Cru" to "Crux",
        "Cir" to "Circinus"
    )
}